
<div class="row"  style="margin-top: 65px; ">
    <div class="jumbotron">
        <h1>Consultas HN 2021</h1>
        <p>Bienvenido al Consultas HN 2021, conulte su centro de votación para las elecciones Honduras 2021</p>
        <p><a class="btn btn-info btn-lg" href="<?php echo $this->basePath(); ?>/consultar">Consultar &raquo;</a></p>
    </div>

    <div class="row">
        <div class="col-sm-12">
            <span class="text-danger" style="font-size: 25px;">Este es un sitio independiente que nada mas está a su disposición para consultar su 
                centro de votación para las elecciones 2021</span>
        </div>
    </div>
</div>